---
title: 'Code for Chapter 9: Analysis of Variance I'
author: "Jim Albert and Maria Rizzo"
subtitle: "R by Example, 2e (2024), Springer"
format:
  html:
    theme: cosmo
    toc: true
    embed-resources: true
    number-sections: true
    number-offset: 8
---

#  Analysis of Variance I

##  Introduction 

```{r}
library(RbyExample)
str(flicker)
```

```{r}
library(RbyExample)
str(flicker)
```

```{r}
is.factor(flicker$Colour)
levels(flicker$Colour)
```

```{r}
unclass(flicker$Colour)
```

```{r}
with(flicker, {
  boxplot(Flicker ~ Colour, ylab = "Flicker")
  stripchart(Flicker ~ Colour, vertical=TRUE)
})
```

```{r}
with(flicker,
  by(Flicker, Colour, FUN=mean))
```

```{r}
meansd <- function(x) c(mean = mean(x), sd = sd(x))
with(flicker,
  by(Flicker, Colour, FUN = meansd))
```

## One-way ANOVA

```{r}
oneway.test(Flicker ~ Colour, data = flicker)
```

```{r}
oneway.test(Flicker ~ Colour, 
            data = flicker, var.equal=TRUE)
```

```{r, flicker-lm}
L <- lm(Flicker ~ Colour, data = flicker)
L
```

```{r}
predict(L)
```

```{r}
M <- aov(Flicker ~ Colour, data = flicker)
model.tables(M, type="means")
```

```{r}
model.tables(M)
```

```{r}
options(show.signif.stars=FALSE)
anova(L)
```

```{r}
plot(L$fit, L$res)
abline(h=0)   #add horizontal line through 0

#Normal-QQ plot of residuals with reference line
qqnorm(L$res)
qqline(L$res)
```

## Comparison of Treatment Means

```{r}
MSE <- 2.3944
t97.5 <- qt(.975, df=16) #97.5th percentile of t
with(flicker, {
  table(Colour)                  #sample sizes
  means <- by(Flicker, Colour, mean)  #treatment means
  outer(means, means, "-")
})
```

```{r}
(n <- table(flicker$Colour))
t97.5 * sqrt(MSE * outer(1/n, 1/n, "+"))
```

```{r}
with(flicker, 
  pairwise.t.test(Flicker, Colour, data = flicker))
```

```{r}
qtukey(.95, nmeans=3, df=16)
```

```{r}
L <- lm(Flicker ~ Colour, data = flicker)
anova(L)
```

```{r}
M <- aov(Flicker ~ Colour, data = flicker)
M
```

```{r}
summary(M)
```

```{r}
TukeyHSD(M)
```

```{r}
plot(TukeyHSD(M))
```

## A Statistical Reference Dataset from NIST

```{r}
resist.dat <- SiRstv
str(resist.dat)
head(resist.dat)
```

```{r}
#Instrument is not a factor
is.factor(resist.dat$Instrument)

#convert Instrument to factor
resist.dat$Instrument <- as.factor(resist.dat$Instrument)

str(resist.dat)      #check our result
```

```{r}
boxplot(Resistance ~ Instrument, data = resist.dat)
stripchart(Resistance ~ Instrument, data = resist.dat,  vertical=TRUE)
```

```{r}
with(resist.dat, { 
by(Resistance, Instrument, 
   FUN=function(x) {c(mean(x), sd(x))})
  })
```

```{r}
L2 <- aov(Resistance ~ Instrument, data = resist.dat)
par(mfrow=c(2, 2), mai=c(.5,.1,.5,.1)) #4 plots on one screen
plot(L2) #residual plots
```

```{r}
plot(TukeyHSD(L2), cex.axis=.7)  #plot the Tukey CI's
```


**ANOVA calculations**

```{r}
anova(L)
```

```{r}
n <- table(flicker$Colour) #sample sizes
a <- length(n)        #number of levels
N <- sum(n)           #total sample size
SS.total <- (N - 1) * var(flicker$Flicker)
#within-sample variances
vars <- by(flicker$Flicker, flicker$Colour, var)   
SSE <- sum(vars * (n - 1))
```

```{r}
#degrees of freedom
print(c(a - 1, N - a, N - 1)) 
```

```{r}
#treatment means
means <- by(flicker$Flicker, flicker$Colour, mean)
grandmean <- sum(flicker$Flicker) / N
SST <- sum(n * (means - grandmean)^2)
print(SST)
```

```{r}

MST <- SST / (a - 1)
MSE <- SSE / (N - a)
statistic <- MST / MSE
p.value <- pf(statistic, df1=a-1, df2=N-a,
              lower.tail=FALSE)
```

```{r}
print(as.data.frame(
   list(MST = MST, MSE = MSE, 
        F = statistic, p = p.value)))
```

