---
title: 'Code for Chapter 10: Analysis of Variance II'
author: "Jim Albert and Maria Rizzo"
subtitle: "R by Example, 2e (2024), Springer"
format:
  html:
    theme: cosmo
    toc: true
    embed-resources: true
    number-sections: true
    number-offset: 9
---

# Analysis of Variance II


## Introduction

## Randomized Block Designs

```{r}
library(bootstrap)
head(scor)
```

```{r}
sapply(scor, mean, data=scor)
```

```{r}
scor.long <- stack(scor)
block <- factor(rep(1:88, times=5))
scor.long <- data.frame(scor.long, block)
```

```{r}
str(scor.long)
```

```{r}
names(scor.long) <- c("score", "exam", "student")
```

```{r}
str(scor.long)
```

```{r}
L <- aov(score ~ exam + student, data=scor.long)
summary(L)
```

```{r}
model.tables(L, cterms="exam")
```

```{r}
model.tables(L, cterms="exam", type="mean")
```

```{r}
CIs <- TukeyHSD(L, which=1)
CIs
```

```{r}
plot(CIs, las=1)
```

```{r}
plot(L, which=1:2)
```

```{r}
boxplot(score ~ student,
        xlab="Student Number", ylab="Score", data=scor.long)
```

## Two-way ANOVA

```{r}
library(RbyExample)
str(poison)
```

```{r}
L <- aov(Time ~ Poison * Treatment, data = poison)
anova(L)
```

```{r}
with(data=poison, expr={
  interaction.plot(Poison, Treatment, response=Time)
  interaction.plot(Treatment, Poison, response=Time)
})
```

```{r}
model.tables(L, type="means")
```

```{r}
TukeyHSD(L, which=c("Poison", "Treatment"))
```

```{r}
#| size: footnotesize
broom::tidy(TukeyHSD(L, which=c("Poison", "Treatment")))
```

```{r}
pairwise.t.test(poison$Time, poison$Poison)
```

## Selected `ggplot` versions of figures in this chapter

```{r}
L <- aov(score ~ exam + student, data=scor.long)
df <- data.frame(residuals=L$resid, fitted.values=L$fitted.values)
```

```{r}
library(ggplot2)
ggplot(df, aes(fitted.values, residuals)) + 
  geom_point() + 
  geom_hline(yintercept = 0) +
  labs(x = "Fitted values", y = "Residuals")
ggplot(df, aes(sample=residuals)) +
  stat_qq() + 
  stat_qq_line() +
  labs(x = "Theoretical Quantiles", y = "Sample Quantiles")
```

```{r}
L <- aov(score ~ exam + student, data=scor.long)
cis <- broom::tidy(TukeyHSD(L, which=1))
cis
```

```{r}
ggplot(cis, aes(x=estimate, y=reorder(contrast, estimate), group=contrast)) +
  geom_point() +
  geom_errorbarh(aes(xmin=conf.low, xmax=conf.high, height=.25)) +
  geom_vline(xintercept=0, linetype="dotted") +
  labs(x="Differences in mean levels of exams", y="") +
  ggtitle("95% family-wise confidence level")
```

```{r}
L <- aov(Time ~ Poison * Treatment, data = poison)
```

```{r}
mtabs <- model.tables(L, type="mean")$tables
df <- as.data.frame(as.table(mtabs$`Poison:Treatment`))
str(df)
```

```{r}
library(ggplot2)
ggplot(df, aes(x=Poison, y=Freq, group=Treatment, color=Treatment)) +
  geom_line(linewidth=2) + labs(y="mean of Time")

ggplot(df, aes(x=Treatment, y=Freq, group=Poison)) +
  geom_line(aes(linetype=Poison)) + labs(y="mean of Time")
```
