---
title: 'Code for Chapter 4: Exploratory Data Analysis'
author: "Jim Albert and Maria Rizzo"
subtitle: "R by Example, 2e (2024), Springer"
format:
  html:
    theme: cosmo
    toc: true
    embed-resources: true
    number-sections: true
    number-offset: 3
---

# Exploratory Data Analysis


## Introduction

## Meet the Data

```{r}
library(RbyExample)
dat <- college
```

```{r}
colleges <- subset(dat, complete.cases(dat))
```

## Comparing Distributions

```{r}stripchart(colleges$Retention, method="stack", 
           pch=19, xlab="Retention Percentage")
```

```{r}
stripchart(Retention ~ Tier, method="stack", pch=19,
           xlab="Retention Percentage",
           ylab="Tier", xlim=c(50, 100), data=colleges)
```

```{r}
# identify(colleges$Retention, colleges$Tier, n=2,
#    labels=colleges$School)
```

```{r}
 b.output <- boxplot(Retention ~ Tier, data=colleges, 
                     horizontal=TRUE, ylab="Tier",
                     xlab="Retention")
```

```{r}
b.output$stats
```

```{r}
b.output$out
```

```{r}
b.output$group
```

## Relationships Between Variables

```{r}
plot(colleges$Retention, colleges$Grad.rate,
  xlab="Retention", ylab="Graduation Rate")
```

```{r}
fit <- line(colleges$Retention, colleges$Grad.rate)
coef(fit)
```

```{r}
plot(colleges$Retention, colleges$Grad.rate, 
     xlab="Retention", ylab="Graduation Rate")
abline(coef(fit))
```

```{r}
plot(colleges$Retention, fit$residuals,
  xlab="Retention", ylab="Residual")
abline(h=0)
```

## Time Series Data

```{r}
BGSU <- RbyExample::bgsu
```

```{r}
plot(BGSU$Year, BGSU$Enrollment)
```

```{r}
fit <- lm(Enrollment ~ Year, data=BGSU)
plot(BGSU$Year, BGSU$Enrollment)
abline(fit)

plot(BGSU$Year, fit$residuals)
abline(h=0)
```

```{r}
BGSU$log.Enrollment <- log(BGSU$Enrollment)
```

```{r}
plot(BGSU$Year, BGSU$log.Enrollment)
fit2 <- lm(log.Enrollment ~ Year, data=BGSU)
abline(fit2)

plot(BGSU$Year, fit2$residuals)
abline(h=0)
```

## Exploring Fraction Data

```{r}
college1 <- subset(colleges, Tier==1)
```

```{r}
stem(college1$Top.10)
```

```{r}
f = c(0.05, 0.1, 0.3, 0.5, 0.7, 0.9, 0.95)
ff = f - (1 - f)
froot = sqrt(2  * f) - sqrt(2 * (1 - f))
flog = 1.15 * log10(f) - 1.15 * log10(1 - f)
D = data.frame(f, ff, froot, flog)
matplot(t(as.matrix(D)), 1:4, type="l", lty=1, lwd=1,
  xlab="Fraction", ylab="Transformed Fraction",
  xlim=c(-1.8, 2), ylim=c(0.5, 4.3))
matplot(t(as.matrix(D[c(1, 4, 7), ])),
  1:4, type="l", lwd=3, lty=1, add=TRUE)
lines(D[c(1, 7), 1], c(1, 1), lwd=2)
lines(D[c(1, 7) ,2], 2 * c(1, 1), lwd=2)
lines(D[c(1, 7), 3], 3 * c(1, 1), lwd=2)
lines(D[c(1, 7), 4], 4 * c(1, 1), lwd=2)
text(c(1.8, 1.5, 1.3, 1.3, 0, 0.5 ,1), 
  c(4, 3, 2, 1, 0.8, 0.8, 0.8),
  c("flog", "froot", "ff", "f", "f=.05", "f=.5", "f=.95"))
```

```{r}
froot <- sqrt(college1$Top.10) - sqrt(100 - college1$Top.10)
flog <- log(college1$Top.10 + 0.5) - log(100 - college1$Top.10 + 0.5)
```

```{r}
stem(froot)
```

```{r}
stem(flog)
```

```{r}
college34 <- subset(colleges, Tier==3 | Tier==4)
college34$froot <- sqrt(college34$Top.10) - 
                   sqrt(100 - college34$Top.10)
```

```{r}
boxplot(froot ~ Tier, data=college34, horizontal=TRUE,
        xlab="Froot(Top 10 Pct)", ylab="Tier")
```

## Selected ggplot versions of the figures

```{r}
library(ggplot2)
ggplot(colleges, aes(y=factor(Tier), x=Retention, fill=factor(Tier))) +
  geom_dotplot(dotsize=.5, binwidth=1) +
  labs(fill="Tier", x="Retention Percentage", y="Tier")
```

```{r}
library(ggplot2)
ggplot(colleges, aes(x=Retention, y=Tier, group=Tier)) +
  geom_boxplot() + ylab("Tier")
ggplot(colleges, aes(x=Retention, y=Tier, group=Tier)) +
  geom_violin() + ylab("Tier")
```

```{r}
fit <- line(colleges$Grad.rate ~ colleges$Retention)
library(ggplot2)

ggplot(colleges, aes(x=Retention, y=Grad.rate)) + 
  geom_point() + ylab("Graduation Rate") +
  geom_abline(intercept=fit$coef[1], slope=fit$coef[2], color=4)

ggplot(colleges, aes(x=Retention, y=fit$residuals)) +
  geom_point() +
  geom_hline(yintercept=0, color=4)
```
