---
title: 'Code for Chapter 12: Multivariate Data'
author: "Jim Albert and Maria Rizzo"
subtitle: "R by Example, 2e (2024), Springer"
format:
  html:
    theme: cosmo
    toc: true
    embed-resources: true
    number-sections: true
    number-offset: 11
---


# Multivariate Data

## Introduction


## Descriptive Statistics


```{r}
library(tidyverse)
```

```{r}
library(knitr, quietly = TRUE)
```

```{r}
library(ggbiplot)
str(crime)
```

```{r}
numvars <- sapply(crime, "is.numeric")
crime1 <- subset(crime, select = numvars)
head(crime1, 2)
```

```{r}
crime |>
  select(where(is.numeric)) -> crime2 
head(crime2, 2)
```

```{r}
identical(crime1, crime2)
```

```{r}
anyNA(crime)
```

```{r}
colMeans(crime1)
```

```{r}
sapply(crime1, median)
```

```{r}
crime |> 
  summarize(across(where(is.numeric), mean))
```

```{r}
crime1 |> 
  summarize(across(everything(), median))
```

```{r}
crime |>
  summarize(across(where(is.numeric), median))
```

```{r}
crime |>
  group_by(region) |>
  summarize(across(where(is.numeric), mean))
```

```{r}
knitr::kable(round(cor(crime1), 2))
```

## Transforming Data


```{r}
means <- colMeans(crime1)
cdata <- sweep(crime1, MARGIN = 2, STATS = means)
```

```{r}
round(colMeans(cdata), 7)
```

```{r}
s <- sapply(crime1, FUN="sd")
scaled <- sweep(crime1, MARGIN = 2, STATS = s, FUN = "/")
```

```{r}
sapply(scaled, "sd")
```

```{r}
means <- colMeans(crime1)
s <- sapply(crime1, FUN = "sd")
crime1 |>
  sweep(MARGIN = 2, STATS = means, FUN = "-") |>
  sweep(MARGIN = 2, STATS = s, FUN = "/") -> crime1_01
```

```{r}
center_scale <- function(x) {
  means <- colMeans(x, na.rm = TRUE)
  s <- apply(x, MARGIN=2, FUN="sd", na.rm = TRUE)
  x |>
    sweep(MARGIN = 2, STATS = means, FUN = "-") |>
    sweep(MARGIN = 2, STATS = s, FUN = "/") -> y
  return(y)
}
```

```{r}
crime1_01 <- center_scale(crime1)
```

```{r}
round(colMeans(crime1_01), 7)
sapply(crime1_01, FUN = "sd")
```

```{r}
cor_before <- cor(crime1)
cor_after <- cor(crime1_01)
all.equal(cor_before, cor_after)
```

```{r}
# center columns to mean 0
crime1 |> 
  mutate(across(everything(), ~ .x - mean(.x))) -> ccrime1
```

```{r}
# scale columns to variance 1
crime1 |> 
  mutate(across(everything(), ~ .x / sd(.x))) -> scrime1
```

```{r}
# center and scale within columns
crime1 |> 
  mutate(across(everything(), ~ (.x - mean(.x)) / sd(.x))) -> cscrime1
```

```{r}
ccrime1 |>
  summarize(across(everything(), ~ round(mean(.x), 7)))
scrime1 |>
  summarize(across(everything(), sd))
cscrime1 |>
  summarize(across(everything(), ~ round(mean(.x), 7)))
cscrime1 |>
  summarize(across(everything(), sd))
```

## Scatterplots

```{r}
crimes <- crime[c(2:8, 10)] 
```

```{r}
pairs(crimes[1:4], gap=0, pch=20, col=4)
```

```{r}
library(lattice)
```

```{r}
splom(crimes[1:4], 
      pscales = 0, cex = .5, lwd = 2, 
      type = c("p", "r"))
```

```{r}
splom(~crimes[1:4] | region, data = crimes, 
      pscales = 0, cex = .5, type=c("p", "smooth"),
      varname.cex = .75)
```

## Correlation Plots

```{r}
library(corrplot)
corrplot(cor(USArrests))
corrplot(cor(USArrests), 
         addCoef.col = 'black', number.cex = 2, 
         tl.pos = 'd')
```

```{r}
library(corrplot)
```

```{r}
x <- crime[, 2:8]
corx <- cor(x)
corrplot(corx, method = "ellipse")
```

```{r}
corrplot(corx, type="upper",
         method = "square",
         diag = FALSE, tl.pos = "td")
corrplot(corx, add=TRUE, 
         type ="lower", 
         method = "number", 
         diag = FALSE, tl.pos = "l")
```

```{r}
library(FactoMineR)
data(decathlon)
names(decathlon)
```

```{r}
corrdeca <- cor(decathlon[1:10])
corrplot(corrdeca)
```

```{r}
corrplot(corrdeca, order="FPC")
```

## Principal Components Analysis

```{r}
table(decathlon$Competition)
events <- subset(decathlon, 
                 decathlon$Competition == "OlympicG",
                 select = 1:10)
```

```{r}
decathlon |>
  filter(Competition == "OlympicG") |>
  select(1:10) -> events
```

```{r}
events |> 
  mutate(across(everything(), ~ .x / sd(.x))) -> events1
```

```{r}
prcomp(events, scale. = TRUE, rank. = 5) -> pca1
summary(pca1)
```

```{r}
S <- cov(events1)
ev <- eigen(S)
dim(ev$vectors)
round(ev$values, 3)
```

```{r}
lambda <- ev$values
prop_var <- lambda / sum(lambda)
cum_prop <- cumsum(lambda) / sum(lambda)
rbind(prop_var[1:5], cum_prop[1:5])
```

```{r}
screeplot(pca1)
screeplot(pca1, type = "lines")
```

```{r}
round( pca1$rotation[, 1:3], 3)
```

```{r}
biplot(pca1, cex=c(.5,.5))
```

```{r}
pca <- prcomp(events, scale. = TRUE)
ggbiplot(pca, varname.color = "blue")
```

```{r}
library(FactoMineR)
PCA(events)
```

```{r}
# plots only
PCA(events, graph=FALSE) -> pca
plot(pca, choix = "ind")
plot(pca, choix = "var")
```

```{r}
pca2 <- princomp(events1) 
summary(pca2)
```

## Cluster Analysis

```{r}
library(MASS, warn.conflicts = FALSE)
data(mammals)
d <- dist(log(mammals))
(h <- hclust(d, method = "complete"))
```

```{r}
bigmammals <- subset(mammals, 
                     subset = (body > median(body)))
```

```{r}
d <- dist(log(bigmammals))
h <- hclust(d, method = "complete")
```

```{r}
plot(h)
```

```{r}
head(h$merge)
```

```{r}
rownames(bigmammals)[c(10, 12)]
```

```{r}
log(bigmammals)[c(10, 12), ]
```

